services:
  server:
    image: shlinkio/shlink:5
    restart: always
    ports:
      - 8080:8080
    environment:
      DB_DRIVER: sqlite
      DEFAULT_DOMAIN: ${SHLINK_DOMAIN}
      IS_HTTPS_ENABLED: false
      GEOLITE_LICENSE_KEY: ${SHLINK_GEOLITE_LICENSE_KEY}
    volumes:
      - ./data:/etc/shlink/data/
