services:
  promtail:
    image: grafana/promtail
    container_name: promtail
    command: -config.file=/etc/promtail/config.yaml
    restart: unless-stopped
    volumes:
      - ./config.yaml:/etc/promtail/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock
